#ifndef Frm_KeyEvent_H
#define Frm_KeyEvent_H

#include "hmifrm_abstractevent.h"

enum KeyEvent
{
    KEYEVENT_NONE = 0,
    KEYEVENT_POWER_PRESS,
    KEYEVENT_POWER_RELEASE,
    KEYEVENT_POWER_LONGPRESS,
    KEYEVENT_POWER_LONGRELEASE,
    KEYEVENT_EQ_PRESS,          // 5
    KEYEVENT_EQ_RELEASE,
    KEYEVENT_EQ_LONGPRESS,
    KEYEVENT_EQ_LONGRELEASE,
    KEYEVENT_BAND_PRESS,
    KEYEVENT_BAND_RELEASE,      //10
    KEYEVENT_MUTE_PRESS,
    KEYEVENT_MUTE_RELEASE,
    KEYEVENT_USB_PRESS,
    KEYEVENT_USB_RELEASE,
    KEYEVENT_NAVI_PRESS,        //15
    KEYEVENT_NAVI_RELEASE,
    KEYEVENT_HOME_PRESS,
    KEYEVENT_HOME_RELEASE,
    KEYEVENT_BACK_PRESS,
    KEYEVENT_BACK_RELEASE,      //20
    KEYEVENT_ENCODER_LEFT,
    KEYEVENT_ENCODER_RIGHT,
    KEYEVENT_ENCODER_PRESS,
    KEYEVENT_ENCODER_RELEASE,
    KEYEVENT_PHONE_PRESS,       //25
    KEYEVENT_PHONE_RELEASE,
    KEYEVENT_PHONE_LONGPRESS,
    KEYEVENT_PHONE_LONGRELEASE,
    KEYEVENT_SETUP_PRESS,
    KEYEVENT_SETUP_RELEASE,     //30
    KEYEVENT_VOL_UP_PRESS,
    KEYEVENT_VOL_UP_RELEASE,
    KEYEVENT_VOL_UP_LONGPRESS,
    KEYEVENT_VOL_UP_LONGRELEASE,
    KEYEVENT_VOL_DN_PRESS,      //35
    KEYEVENT_VOL_DN_RELEASE,
    KEYEVENT_VOL_DN_LONGPRESS,
    KEYEVENT_VOL_DN_LONGRELEASE,
    KEYEVENT_SEEK_UP_PRESS,
    KEYEVENT_SEEK_UP_RELEASE,   //40
    KEYEVENT_SEEK_UP_LONGPRESS,
    KEYEVENT_SEEK_UP_LONGRELEASE,
    KEYEVENT_SEEK_DN_PRESS,
    KEYEVENT_SEEK_DN_RELEASE,
    KEYEVENT_SEEK_DN_LONGPRESS, //45
    KEYEVENT_SEEK_DN_LONGRELEASE,
    KEYEVENT_DISP_PRESS,
    KEYEVENT_DISP_RELEASE,
    KEYEVENT_DISP_LONGPRESS,
    KEYEVENT_DISP_LONGRELEASE,  //50
    KEYEVENT_STW_MUTE_PRESS,
    KEYEVENT_STW_MUTE_RELEASE,
    KEYEVENT_STW_MODE_PRESS,
    KEYEVENT_STW_MODE_RELEASE,
    KEYEVENT_ASR_PRESS,         //55
    KEYEVENT_ASR_RELEASE,
    KEYEVENT_ASR_LONGPRESS,
    KEYEVENT_ASR_LONGRELEASE,
    KEYEVENT_LINK_PRESS,
    KEYEVENT_LINK_RELEASE,      //60
    KEYEVENT_SEEK_UP_LONGPRESS_2S,
    KEYEVENT_SEEK_DN_LONGPRESS_2S,
    KEYEVENT_STW_SEEK_UP_PRESS,
    KEYEVENT_STW_SEEK_UP_RELEASE,
    KEYEVENT_STW_SEEK_UP_LONGPRESS,
    KEYEVENT_STW_SEEK_UP_LONGRELEASE,
    KEYEVENT_STW_SEEK_DN_PRESS,
    KEYEVENT_STW_SEEK_DN_RELEASE,
    KEYEVENT_STW_SEEK_DN_LONGPRESS,
    KEYEVENT_STW_SEEK_DN_LONGRELEASE,

    KEYEVENT_ETM_ENTRY,                 //Enter Engineer Mode
    KEYEVENT_FACTORY_MODE_ENTRY,       //Enter Factory Mode
    KEYEVENT_CARPLAY_TEST,
    KEYEVENT_NAVI2PHONE_PRESS, 
    KEYEVENT_NAVI2PHONE_RELEASE,
    KEYEVENT_MAX
};

class Frm_KeyEvent : public Frm_AbstractEvent
{

public:

    Frm_KeyEvent(Type type = QEvent::None, KeyEvent eventID = KEYEVENT_NONE);

    ~Frm_KeyEvent();

    //KEY event ID
    inline KeyEvent getFuncID(){return keyEventID;}

private:
    //key event ID
    KeyEvent keyEventID;
};

#endif // Frm_KeyEvent_H
